site_name: Demo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          #rendering:
          options:
            show_if_no_docstring: False
            filters: null

nav:
  - Home: index.md
